FROM python:3.9-alpine
ENV PROJECT_ROOT=/home/user/projects/coding/smart-containers/webApp

RUN mkdir -p /code
WORKDIR /code
COPY . /code

RUN apk add --no-cache bash
RUN apk add --no-cache postgresql
RUN pip install --no-cache-dir -r requirements.yml


COPY init.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/init.sh
ENTRYPOINT ["init.sh"]
EXPOSE 8000
EXPOSE 1883