# Generated by Django 4.1.7 on 2023-05-14 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "container_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("container_content", models.CharField(max_length=100)),
                ("container_door_closed", models.BooleanField()),
                ("container_start", models.CharField(max_length=101)),
                ("container_destination", models.CharField(max_length=100)),
                ("container_time", models.DateTimeField()),
            ],
            options={
                "ordering": ["container_id"],
            },
        ),
        
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sensor_type", models.CharField(max_length=10)),
                ("sensor_data", models.CharField(max_length=100)),
                ("sensor_time", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="sensor.container",
                    ),
                ),
            ],
            options={
                "ordering": ["sensor_time"],
            },
        ),
    ]
