# Generated by Django 4.2 on 2023-05-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='data_type',
            new_name='dataType',
        ),
    ]
