# Generated by Django 4.1.7 on 2023-05-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('GPS', 'GPS'), ('TEMP', 'Temperature'), ('HUM', 'Humidity'), ('DOOR', 'Door'), ('ACCEL', 'Acceleration')], max_length=100),
        ),
    ]
