# Generated by Django 4.1.7 on 2023-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensordata_sensor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
