# Generated by Django 4.2 on 2023-05-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_user_last_login_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
