# Generated by Django 4.2 on 2023-05-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpReq',
        ),
    ]
