# Generated by Django 4.1.7 on 2023-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.IntegerField()),
                ('container_content', models.CharField(max_length=100)),
                ('container_door_closed', models.BooleanField()),
                ('container_start', models.CharField(max_length=100)),
                ('container_destination', models.CharField(max_length=100)),
                ('container_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['container_id'],
            },
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=10)),
                ('sensor_data', models.CharField(max_length=100)),
                ('sensor_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['sensor_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
