# Generated by Django 4.1.7 on 2023-05-14 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0002_sensordata_delete_sensor_data_remove_container_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
