# Generated by Django 4.1.7 on 2023-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0004_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_start",
            field=models.CharField(max_length=101),
        ),
    ]
