# Generated by Django 4.1.7 on 2023-05-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_alter_container_container_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor_Data',
        ),
    ]
