# name of your application
APPLICATION = test_waterleak

# If no BOARD is found in the environment, use this default:
BOARD ?= feather-nrf52840

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../../RIOT

USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq

include $(RIOTBASE)/Makefile.include
